name: Create GitHub Release

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'
    paths:
      - 'version.txt'
      
jobs:
  create_foundry_release:
    runs-on: ubuntu-latest
    name: Create GitHub Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release
        id: create-github-release
        uses: foundryvtt-dcc/foundry-release-action@main
        with:
          actionToken: ${{ secrets.GITHUB_TOKEN }}
          manifestFileName: 'module.json'
          manifestProtected: true
